= powERGful: Bike Workout DSL
:name: powERGful
:toc:

image:https://gitlab.com/CodeLenny/bike-workout-dsl/badges/master/pipeline.svg[link="https://gitlab.com/CodeLenny/bike-workout-dsl/commits/master",title="pipeline status"]
image:https://codecov.io/gh/CodeLenny/bike-workout-dsl/branch/master/graph/badge.svg[link="https://codecov.io/gh/CodeLenny/bike-workout-dsl",title="code coverage"]

A powerful DSL for creating bike workouts that can be compiled to ERG and other workout formats.
Files written in {name} should be easy to read,
while being concise.

== Example

.Basic Example
[source]
----
"Warm up" 5m at 75% FTP / 60% FTHR
  @0m "5 minute warmup!"
> "Get your legs spinning with a 5 minute warm up."

"Work" 10m at 100% FTP / 100% FTHR
  @0m "10 minutes of 100% FTP to get going!"
  @1m "Make sure you're in a good cadence."
  @9:00 "Finish strong!"
----

== Installation and Usage

=== Pre-Requisites

You must have Node.js and NPM installed on your computer.

=== For Programmatic Usage

If you want to use {name} from TypeScript or JavaScript, install `powergful` via NPM:

.Programmatic Installation
[source,sh]
----
npm install --save powergful
----

Then you can import {name} into your application:

.TypeScript Import
[source,typescript]
----
import BikeWorkoutDSL from "powergful";
----

.JavaScript Require
[source,js]
----
const BikeWorkoutDSL = require("powergful");
----

=== For Command Line Usage

If you just want to run {name} on the command line, you can install {name} globally on your computer, or install locally.

.Global Installation
[source,sh]
----
npm install --global powergful
powergful --help
powergful convert --outdir $(pwd)/out my-workout.workout
----

.Local Installation
[source,sh]
----
mkdir workouts
cd workouts
npm install powergful # installs in => .node_modules
$(npm bin)/powergful --help
.node_modules/bin/powergful --help
----

== Status

{name} is in a pre-beta state.  This means that there are still rough edges,
and syntax may be tweaked without warning.

Once {name} is in beta, the language will be stable and conform to semantic versioning,
so minor versions will be backwards compatible.

link:https://github.com/CodeLenny/bike-workout-dsl/milestone/1[Issues blocking v0.1.0]
